apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleprojet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleprojet
  template:
    metadata:
      labels:
        app: sampleprojet
    spec:
      containers:
        - name: sampleprojet
          image: ayoubajdour/sampleprojet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sampleprojet
spec:
  selector:
    app: sampleprojet
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer